### ISSUE TITLE
Suggestions for combining

### ISSUE THREAD

**Issue by Big-Shark** [formapro/telegram-bot-php#4]
Hi guys, congratulations with release.

We also recently wrote a library(https://github.com/tg-bot-api/bot-api-base) for writing bots in php, with a fairly similar API, but with a bit more functionality, and we have suggestions for combining efforts and libraries,  what do you think about it?

@makasim @greblov

**Comment by makasim** [comment]
Do you see how this could be achieved?

**Comment by Big-Shark** [comment]
@makasim I think we can discuss about this in Telegram https://t.me/Big_Shark
